service: s3-copy-files
frameworkVersion: "2"

provider:
    name: aws
    runtime: nodejs12.x
    lambdaHashingVersion: 20201221
    stage: dev
    region: us-east-1

 iamRoleStatements:
   - Effect: "Allow"
     Action:
       - "s3:GetObject"
       - "s3:PutObject"
     Resource: "arn:aws:s3:::src-kitten/*"
   - Effect: "Allow"
     Action:
       - "s3:GetObject"
       - "s3:PutObject"
     Resource: "arn:aws:s3:::dest-kitten/*"

functions:
    fileOperations:
        handler: handler.triggerS3Operations
        name: file-operations
        events:
            - s3:
                bucket: "src-kitten"
                event:
                    - s3:ObjectCreated:*